### ISSUE TITLE
Bug: Array to string conversion

### ISSUE THREAD

**Issue by MrJmpl3** [supliu/laravel-query-monitor#8]
```
[2020-07-30 07:26:35] local.ERROR: Array to string conversion {"exception":"[object] (ErrorException(code: 0): Array to string conversion at /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/laravel/framework/src/Illuminate/Support/Str.php:449)
[stacktrace]
#0 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/laravel/framework/src/Illuminate/Support/Str.php(449): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/supliu/laravel-query-monitor/src/ListenQueries.php(77): Illuminate\\Support\\Str::replaceArray()
#2 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Supliu\\LaravelQueryMonitor\\ListenQueries->Supliu\\LaravelQueryMonitor\\{closure}()
#3 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/react/stream/src/Util.php(71): Evenement\\EventEmitter->emit()
#4 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\\Stream\\Util::React\\Stream\\{closure}()
#5 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/react/stream/src/DuplexResourceStream.php(193): Evenement\\EventEmitter->emit()
#6 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/react/event-loop/src/StreamSelectLoop.php(245): React\\Stream\\DuplexResourceStream->handleData()
#7 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/react/event-loop/src/StreamSelectLoop.php(212): React\\EventLoop\\StreamSelectLoop->waitForStreamActivity()
#8 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/supliu/laravel-query-monitor/src/ListenQueries.php(90): React\\EventLoop\\StreamSelectLoop->run()
#9 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/supliu/laravel-query-monitor/src/Commands/MonitorCommand.php(57): Supliu\\LaravelQueryMonitor\\ListenQueries->run()
#10 [internal function]: Supliu\\LaravelQueryMonitor\\Commands\\MonitorCommand->handle()
#11 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array()
#12 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#14 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod()
#15 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call()
#16 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#17 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#18 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#19 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/symfony/console/Application.php(911): Illuminate\\Console\\Command->run()
#20 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand()
#21 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun()
#22 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#23 /home/vagrant/ocasani-laravel-api-recave-see-cliente/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#24 /home/vagrant/ocasani-laravel-api-recave-see-cliente/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#25 {main}
"} 
```

**Comment by fozbek** [comment]
Same here

**Comment by sriniwaas510** [comment]
I am getting the same error
